# Values for secrets-provider. All missing values need to be supplied by the customer.
# Example values provided here:
# DAP https://docs.conjur.org/<PATH TBD>
# Conjur OSS https://docs.conjur.org/<PATH TBD>

rbac:
  # Indicates whether the Secrets Provider ServiceAccount, Role, and RoleBinding should be created. This should be set
  # to true unless resources with the proper permissions exist in the namespace.
  create: true
  roleName: secrets-provider-role
  roleBindingName: secrets-provider-role-binding
  serviceAccount:
    # Name of the service account for the Secrets Provider.
    name: secrets-provider-service-account

secretsProvider:
  image: cyberark/secrets-provider-for-k8s
  tag: 1.0.0
  imagePullPolicy: IfNotPresent
  name: cyberark-secrets-provider

# OPTIONAL: Additional labels to apply to Job resource.
labels: {}
annotations: {}

environment:
  # Array of Kubernetes Secret names that applications consume, and whose value is sourced in DAP/Conjur.
  # For example, [k8s-secret1,k8s-secret2]
  k8sSecrets:
  conjur:
    # DAP/Conjur account name as defined during initial DAP/Conjur configuration.
    account:
    # URL of service defined for DAP Follower/Conjur.
    applianceUrl:
    # URL for the Kubernetes authenticator with which the Secrets Provider will authenticate.
    authnUrl:
    # Host that authenticates Secrets Provider to DAP/Conjur.
    authnLogin:
    sslCertificate:
      # Name of ConfigMap that holds the public SSL certificate required for connecting to Follower/Conjur.
      name: cert-config-map
      # Value that stores the public SSL certificate required for connecting to Follower/Conjur.
      # This value should be passed in when installing the chart.
      value:
