FROM golang:1.12.0-alpine3.9
MAINTAINER Conjur Inc.
LABEL id="secrets-provider-for-k8s-junit-processor"

WORKDIR /test

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev \
               bash

RUN go get -u github.com/jstemmer/go-junit-report
