FROM golang:1.12.0-alpine3.9
MAINTAINER Conjur Inc.
LABEL id="cyberark-secrets-provider-for-k8s-test-runner"

WORKDIR /cyberark-secrets-provider-for-k8s

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /cyberark-secrets-provider-for-k8s/

RUN go mod download

COPY . .

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
