FROM golang:1.19-alpine
MAINTAINER CyberArk Software Ltd.
LABEL id="secrets-provider-for-k8s-e2e-test-runner"

WORKDIR /secrets-provider-for-k8s

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY ./go.mod ./go.sum /secrets-provider-for-k8s/

RUN go mod download

COPY . .

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m", "-tags", "e2e", "./e2e/..." ]
