---
# This policy defines a layer of whitelisted identities permitted to authenticate to the authn-k8s endpoint.
# This policy is needed for both DEV and TEST environments
- !policy
  id: conjur/authn-k8s/${AUTHENTICATOR_ID}/apps
  annotations:
    description: Identities permitted to authenticate
  body:
    - !layer
      annotations:
        description: Layer of authenticator identities permitted to call authn svc
    - &hosts
      - !host
        id: test-app
        annotations:
          authn-k8s/namespace: ${APP_NAMESPACE_NAME}
          authn-k8s/service-account: secrets-provider-sa
          kubernetes/authentication-container-name: cyberark-secrets-provider

    - !grant
      role: !layer
      members: *hosts
# This policy defines an authn-k8s endpoint, CA creds and a layer for whitelisted identities permitted to authenticate to it
# This policy is needed for both DEV and TEST environments
- !policy
  id: conjur/authn-k8s/${AUTHENTICATOR_ID}
  annotations:
    description: Namespace defs for the Conjur cluster in dev
  body:
    - !webservice
      annotations:
        description: authn service for cluster

    - !policy
      id: ca
      body:
        - !variable
          id: cert
          annotations:
            description: CA cert for Kubernetes Pods.
        - !variable
          id: key
          annotations:
            description: CA key for Kubernetes Pods.

    # define layer of whitelisted authn ids permitted to call authn service
    - !layer users

    - !permit
      resource: !webservice
      privilege: [ read, authenticate ]
      role: !layer users

- !grant
  role: !layer conjur/authn-k8s/${AUTHENTICATOR_ID}/users
  members:
    - !layer conjur/authn-k8s/${AUTHENTICATOR_ID}/apps
