---
- !policy
  id: secrets-${index}
  body:
    - &variables
      - !variable app-secret-1
      - !variable app-secret-2
      - !variable app-secret-3
      - !variable app-secret-4
      - !variable app-secret-5

    - !layer users

    - !permit
      resources: *variables
      role: !layer users
      privileges: [ read, execute ]

- !grant
  role: !layer secrets-${index}/users
  members:
    - !layer conjur/authn-k8s/${AUTHENTICATOR_ID}/apps
