apiVersion: {{ include "conjur.rbac-api" . }}
kind: Role
metadata:
  name: {{ .Values.rbac.roleName }}
  namespace: {{ .Release.namespace }}
rules:
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: [ "get", "update" ]
