apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.roleName }}
  namespace: {{ .Release.namespace }}
rules:
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: [ "get", "update" ]
