apiVersion: {{ include "conjur.deploy-api" . }}
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
      containers:
      - image: {{ .Values.secretsProvider.image }}:{{ .Values.secretsProvider.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.secretsProvider.name }}
        env:
        - name: SECRETS_DESTINATION
          value: k8s_secrets

        - name: CONTAINER_MODE
          value: init

        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name

        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace

        - name: CONJUR_APPLIANCE_URL
          value:  {{ .Values.environment.conjur.applianceUrl | quote }}

        - name: CONJUR_AUTHN_URL
          value:  {{ .Values.environment.conjur.authnUrl | quote }}

        - name: CONJUR_ACCOUNT
          value:  {{ .Values.environment.conjur.account | quote }}

        - name: CONJUR_SSL_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.environment.conjur.sslCertificate.name | quote }}
              key: ssl-certificate

        - name: CONJUR_AUTHN_LOGIN
          value:  {{ .Values.environment.conjur.authnLogin | quote }}

        - name: SUPPORT_MULTIPLE_APPS
          value: "true"

        - name: K8S_SECRETS
          value: {{ .Values.environment.k8sSecrets | join "," }}

        {{- if .Values.environment.debug }}
        - name: DEBUG
          value: "true"
        {{- end }}
      restartPolicy: Never
  backoffLimit: 0
