apiVersion: v1
kind: Secret
metadata:
  name: test-k8s-secret
type: Opaque
stringData:
  conjur-map: |-
    secret: secrets/test_secret
    var_with_spaces: secrets/var with spaces
    var_with_pluses: secrets/var+with+pluses
  non-conjur-key: some-value
