apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
{{- with .Values.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
{{- with .Values.labels }}
      labels:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
      containers:
      - image: {{ .Values.secretsProvider.image }}:{{ .Values.secretsProvider.tag }}
        imagePullPolicy: {{ .Values.secretsProvider.pullPolicy }}
        name: {{ .Values.secretsProvider.name }}
        env:
        - name: SECRETS_DESTINATION
          value: k8s_secrets

        - name: CONTAINER_MODE
          value: init

        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name

        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace

        - name: CONJUR_APPLIANCE_URL
          value:  {{ .Values.environment.conjur.applianceUrl | quote }}

        - name: CONJUR_AUTHN_URL
          value:  {{ .Values.environment.conjur.authnUrl | quote }}

        - name: CONJUR_ACCOUNT
          value:  {{ .Values.environment.conjur.account | quote }}

        - name: CONJUR_SSL_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.environment.conjur.sslCertificate.name | quote }}
              key: ssl-certificate

        - name: CONJUR_AUTHN_LOGIN
          value:  {{ .Values.environment.conjur.authnLogin | quote }}

        - name: K8S_SECRETS
          value: {{ .Values.environment.k8sSecrets | join "," }}

        {{- if .Values.environment.debug }}
        - name: DEBUG
          value: true
        {{- end }}
      restartPolicy: Never
  backoffLimit: 0
