#!/bin/bash
set -euo pipefail

source bin/build_utils
helm_version=3.3.0

docker run --rm \
  -v $PWD/helm/secrets-provider:/root/helm/secrets-provider \
  -v $PWD/helm-artifacts/:/root/helm-artifacts \
  --workdir /root/helm-artifacts \
  alpine/helm:${helm_version} package ../helm/secrets-provider
