#!/bin/bash

# Runs a Helm unit test using the 'helm-unittest' Helm plugin.
# Reference: https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md

# Execute from the parent (chart) directory as required to run unittest
cd "../$(dirname "$0")"

source ./tests/utils.sh

banner $BOLD "Running Helm unit tests for chart \"conjur-config-cluster-prep\""

# Install the 'helm-unittest' plugin if it hasn't been install already
if [[ ! "$(helm plugin list | awk '/^unittest\t/{print $1}')" ]]; then
    echo "Installing 'helm-unittest' Helm plugin"
    helm plugin install https://github.com/quintush/helm-unittest
fi

# Run a Helm unit test
helm unittest . --helm3
