#!/bin/bash
set -euo pipefail

cat << EOL
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-env-app
  name: test-env-app
spec:
  replicas: 1
  selector:
    app: test-env-app
  template:
    metadata:
      labels:
        app: test-env-app
    spec:
      serviceAccountName: ${APP_NAMESPACE_NAME}-sa
      containers:
      - image: debian
        name: test-app
        command: ["sleep"]
        args: ["infinity"]
        env:
          - name: TEST_SECRET
            valueFrom:
              secretKeyRef:
                name: test-k8s-secret
                key: secret
          - name: NON_CONJUR_SECRET
            valueFrom:
              secretKeyRef:
                name: test-k8s-secret
                key: non-conjur-key
EOL

