#!/bin/bash

set -euo pipefail
cat << EOL
---
# This policy defines a layer of whitelisted identities permitted to authenticate to the authn-k8s endpoint.
# This policy is needed for both DEV and TEST environments
- !policy
  id: conjur/authn-k8s/${AUTHENTICATOR_ID}/apps
  annotations:
    description: Identities permitted to authenticate
  body:
    - !layer
      annotations:
        description: Layer of authenticator identities permitted to call authn svc
    - &hosts
      - !host
        id: ${APP_NAMESPACE_NAME}/*/*
        annotations:
          kubernetes/authentication-container-name: cyberark-secrets-provider-for-k8s

      # This host will not have permissions on Conjur secrets to test this use-case
      - !host
        id: ${APP_NAMESPACE_NAME}/service_account/${APP_NAMESPACE_NAME}-sa
        annotations:
          kubernetes/authentication-container-name: cyberark-secrets-provider-for-k8s

    - !grant
      role: !layer
      members: *hosts
EOL
