#!/bin/bash

set -euo pipefail
cat << EOL
# Should be loaded into root
- !policy
  id: secrets
  body:
    - &variables
      - !variable test_secret
      - !variable another_test_secret
      - !variable var with spaces
      - !variable var+with+pluses

    - !layer users

    - !permit
      resources: *variables
      role: !layer users
      privileges: [ read, execute ]

- !grant
  role: !layer secrets/users
  members:
    - !host conjur/authn-k8s/${AUTHENTICATOR_ID}/apps/${APP_NAMESPACE_NAME}/*/*
EOL
